### ISSUE TITLE
REQUEST: Add a debug toggle to the core options

### ISSUE THREAD

**Issue by ScOULaris** [libretro/mame2003-libretro#318]
Right now there is no way to enable the Debug option in lr-mame2003. On MAME for Windows running mame for a ROM with the -debug parameter alllows you to run altered versions of ROMs (e.g. romhacks). I'd love to be able to run a modified version of Mortal Kombat 2 called MK2+ in Retropie, but without a debug option I'm unable to do so.

Would it be possible to include a Debug on/off option in the Core Options? Or maybe some other option that allows for the checksum check to be skipped for a particular ROM?

**Comment by markwkidd** [comment]
I have added an experimental new core option to disable the ROM hashcheck. If you update from source you should see this.

I don't know how this is supposed to work and I don't have any hacked romsets to try myself.

Please test your hacked romset with the original mame 0.78's debug option first to make sure it works at all: https://mirrors.xmission.com/mame/releases/mame078b.zip

Then please post back here to share what happens when you try the new mame2003 core option.

Note that you will have to change the core option, then close mame2003, then start mame2003 in order for the change to take effect.

**Comment by markwkidd** [comment]
In retrospect, we're probably not going to disable the CRC checks via an option, but with mame2003-plus-libretro there is the possibility of selectively adding full support to romhacks that bring unique features. Feel free to talk about specific romsets to add over in that repo: https://github.com/libretro/mame2003-plus-libretro
