### ISSUE TITLE
[Wii U] In game controller bug when USB keyboard is connected

### ISSUE THREAD

**Issue by cucholix** [libretro/mame2003-libretro#335]
This is fairly weird bug.
Steps to reproduce the bug:
- attach an USB keyboard and/or USB mouse to Wii U 
- set Unified Menu Controls = ON (in order to navigate normally RA menu, otherwise gamepads don't respond with USB keyboard attached)
- start a mame2003 content
- press ZL in the GamePad, it will bring "watchpoints" setting (?)
- once you press ZL this watchpoint will set ON, from now on it doesn't respond gamepad inputs properly, also if you exit to menu and return to the game the bug trigger, doesn't matter if you press ZL or not

It doesn't happen with mame2010, both builds are from march 13th

***The issue is pretty similar to what happen with RA when "Unified Menu Controls" is disabled and you connect an USB keyboard, the controller in RA menu goes crazy***

**Comment by markwkidd** [comment]
I have submitted a PR intended to address this: https://github.com/libretro/mame2003-libretro/pull/336

**Comment by markwkidd** [comment]
@cucholix what happens if you try to control the emulator with your keyboard instead of the WiiU keypad? https://docs.libretro.com/guides/retroarch-keyboard-controls/

What happens if you connect the keyboard but Unified Controls is not turned on?

**Comment by cucholix** [comment]
When trying to control mame2003 with keyboard there's no response, and when pressing the "up" key the system crashes:
![img-20180315-wa0028](https://user-images.githubusercontent.com/16081693/37500193-da9c58c2-28a6-11e8-9c75-5051f791c436.jpg)

If I desable Unified Menu Controls I'm not able to navigate through RA since the cursor gets stuck in "up" 
I filled an issue about it https://github.com/libretro/RetroArch/issues/6322

Though it was the normal behavoir due not having Unified Menu Controls enabled.

**Comment by markwkidd** [comment]
Adding to the record for anyone else investigating this:

There is no sign of mame2003 using the Wii or WiiU compiler flags to do anything to the input code that isn't happening on other platforms:
```
MINGW64 ~/mame2003-libretro
$ grep -r -i wii
Makefile:else ifeq ($(platform), wii)
Makefile:else ifeq ($(platform), wiiu)
Makefile:   PLATCFLAGS += -DGEKKO -DWIIU -mwup -mcpu=750 -meabi -mhard-float -D__ppc__ -D__POWERPC__ -Dstricmp=strcasecmp
src/drivers/suprnova.c:  DSW1(8)   ||      VIEWIII-A      SPCII-A   W24257 LH540202      ||
```

**Comment by cucholix** [comment]
Tested with a wireless mouse connected instead a keyboard and the issue still happens

**Comment by Ploggy** [comment]
I pretty much have had the same experience Cucholix using the keyboard on Mame2003

I got greeted by this as soon as i tried to use the keyboard with a fresh install with the latest nightly :)
The Gamepad didn't respond initially (Probably because I didn't set unified controls) So I tried to use the keyboard and this happened..
![20180316_121130](https://user-images.githubusercontent.com/1160255/37521572-1fdd9460-2919-11e8-8e70-c24143ced2c7.jpg)

So I restarted the WiiU and unplugged the keyboard so I can set unified controls and save the cfg first ;)
This time the Gamepad worked but trying the keyboard again caused the same DSI error?

Again I restarted to see if I was having the same issue you described in the Mame2003 Core.
I loaded up the Mame2003 core and booted up Black Tiger (Classic) ;) and it seems the controls are wonky.. The character moves to the left by itself and its as if the fire button is held constantly.
I tried to press a key on the keyboard while the game was running and got this DSI Error..
![20180316_122743](https://user-images.githubusercontent.com/1160255/37521605-2f3a37a6-2919-11e8-936b-471cb5abe71a.jpg)


So there's definitely something flaky going on with the keyboard support on WiiU :)

**Comment by markwkidd** [comment]
I speculate that this isn't really a mame2003 issue, but somehow due to the way mame2003 implements keyboard support it is a problem here even when it isn't in mame2010.

I'm really hoping we can attract someone with expertise more specific to this part of the code, but I'm also willing to help keep investigating!

**Comment by cucholix** [comment]
Fixed with @QuarkTheAwesome PR https://github.com/libretro/RetroArch/commit/aeea0e6ca8101e98c1cbf62d59aa29a0243e1433

Thanks!
