### ISSUE TITLE
X-flipped screen on light gun games

### ISSUE THREAD

**Issue by pafffff** [libretro/mame2003-libretro#341]
In some games, the screen is flipped horizontally. For example in othunder.zip

See a description and some suggestions about a possible cause on [https://retropie.org.uk/forum/topic/16898/lr-mame2003-flipping-the-screen-in-some-games/7]

**Comment by markwkidd** [comment]
@pafffff I have started a bounty fundraiser for someone to help fix this issue. you can follow any developments at this issue: https://github.com/libretro/mame2003-libretro/issues/386

If you or someone else reading this would like to contribute to the bounty in order to help move this forward, here is a direct link to the appropriate BountySource page: https://www.bountysource.com/issues/65054242-bounty-10-implement-internal-mame-video-flip-mirroring

**Comment by nayslayer** [comment]
This issue was resolved as a core of #386, then improved on in #391. Those games are playable now.
