### ISSUE TITLE
Screen rotation for vertical games

### ISSUE THREAD

**Issue by JabberwockPL** [libretro/mame2003-libretro#382]
I cannot figure out how the rotation works with this core... And I really did google it hard.

First of all, after compilation (I am compiling with Buildroot for a low-spec ARM device) the core already works as if TATE was enabled, without me changing the option. Which is fine, as the device is portable. However, I would prefer that the vertical games were rotated 180 (with horizontal left as they are), as it would make using the controls much easier. I have tried to experiment with video_rotation, but to no avail. Is there an option (or a portion of the source code) that I could change to obtain the desired result?

By the way, there is one game in my collection, that does that already: Q*bert...

**Comment by dankcushions** [comment]
which video driver are you using?

**Comment by JabberwockPL** [comment]
SDL, as it is the only one that seems to be working on the machine.

**Comment by JabberwockPL** [comment]
Yes, that could be the reason the options are not working wel... Still, there must be a place in the code which decides which way the vertical games are being displayed?

**Comment by dankcushions** [comment]
what MAME does natively is render the screen as the game would. eg, in a vertical shooter, the CRT in the cabinet was literally on its side, so MAME renders that game as if it was rotated 90 (or 270) degrees, AND THEN rotates it later on in the code so the user doesn't have to lie down to play the game :)

what a libretro core does is to do that final rotation operation within the libretro video drivers (eg GL, SDL, etc). if rotation is implemented in the driver (eg, GL), then you see an image like this:

![image](https://user-images.githubusercontent.com/13054748/47028526-73d26000-d161-11e8-8ce1-436f5421658b.png)

if it's not (eg, SDL?), then the rotation won't happen, but i believe the image will still get it's aspect ratio corrected, so you'll get this kind of thing:

![image](https://user-images.githubusercontent.com/13054748/47028994-6b2e5980-d162-11e8-8c41-3ad30bfe48c8.png)

so if you see an image like that, rotation within libretro is NOT happening, even though the image is rotated, confusingly.

the TATE option in the code stops the rotation AND aspect ratio correction, so that people who can physically turn their monitors (or handheld device), can do it that way. they would get an image like:

![image](https://user-images.githubusercontent.com/13054748/47029166-c7917900-d162-11e8-8798-d2c0052177c1.png)

**Comment by dankcushions** [comment]
ps, the reason qbert is a different direction is probably because it has a CRT that is rotated 270 degrees:

https://github.com/libretro/mame2003-libretro/blob/80b83cc3d1340aa1708187e33b568e66f58c9700/src/drivers/gottlieb.c#L1944

most/more vertical games are rotated 90 degrees i think.

**Comment by markwkidd** [comment]
I wonder if there is a possible feature request for RetroArch here so that video drivers without rotation support can handle that some other way.

It seems wrong and unintended to have very different video displaying (ie rotated) from one driver to another.

**Comment by dankcushions** [comment]
yeah the fix is surely to complete the drivers. i don't see an alternative to that. libretro can only communicate to the video hardware via the drivers.

sdl driver does not implement rotation: https://github.com/libretro/RetroArch/blob/master/gfx/drivers/sdl_gfx.c#L563

BUT looks like SDL2 driver does implement it: https://github.com/libretro/RetroArch/blob/master/gfx/drivers/sdl2_gfx.c#L598

@JabberwockPL can you use the SDL2 driver with your hardware?

**Comment by JabberwockPL** [comment]
Finally I understand how this works: the core always displays the game as it is, without any rotation. Any options are ignored, as my driver is not capable of supporting them.

Sadly, I could not make SDL2 (and OpenGL) work (it gives fatal error on init), even though I have tried hard: SDL seems to be incapable of displaying retroarch menu (rgui), so I have to rely on command line. This is rather undesirable for the mobile device (Leapfrog Leapster GS). It might be that people working on hacking those devices will succeed in getting other drivers to work, but for now it is as it is.

Still, you might consider adding another option that would rotate the display only for vertical (or only for horizontal) games.

**Comment by markwkidd** [comment]
I filed the RetroArch issue: https://github.com/libretro/RetroArch/issues/7447

**Comment by markwkidd** [comment]
@JabberwockPL we have a response from bparker, who is one of the RetroArch developers who works hands on with the video drivers. bparker says that "We could implement this, however for low-powered devices it would be unusably slow, as SDL1 is software-rendered."

You can check out the answer here: https://github.com/libretro/RetroArch/issues/7447

I'm afraid this may not be possible

**Comment by JabberwockPL** [comment]
I do not think it would be worth the hassle. I still hope to get something more than SDL running on the device... Unfortunately, there is very little known about the chip, so it might be hard.

Anyway, thank you for the information!
