### ISSUE TITLE
is there a windows version of this libretro?

### ISSUE THREAD

**Issue by estivalet** [libretro/mame2003-libretro#44]
I want to have the same collection that I have in my Pi in Windows

**Comment by dankcushions** [comment]
currently isn't compiling on windows, but i've found the problem. fix forthcoming!

**Comment by estivalet** [comment]
wow thank you very much appreciate the fix. I have different sets of mame, it'd be very cool.

**Comment by dankcushions** [comment]
I think I've fixed this here: https://github.com/dankcushions/mame2003-libretro/tree/windows

annoyingly i can't test as I cannot compile this on windows 7 because the linking stage fails - the command to link all the various mame files is too long for the windows cmd limit. i've tried some shell replacements but nothing seems to work. i'll see if i can get anyone to help me on IRC.

**Comment by dankcushions** [comment]
I figured it out :) Cleaned up and submitted the fix for review: https://github.com/libretro/mame2003-libretro/pull/45

**Comment by dankcushions** [comment]
Sorry, missed one important fix from that PR! #46 - after that windows compiles work fine.
