### ISSUE TITLE
Sound Problem PS Vita Core Mame2003

### ISSUE THREAD

**Issue by nubecitas** [libretro/mame2003-libretro#86]
In the last version of PSVita core Mame2003, works pretty fast but now has  problems with the sound on many games. like (wardner), some sounds are muted and the others are very strange like bad equalized. before the update when the core works slow, the sounds work great, with the optimization, the sound has problems.

Sorry, my english is not very good.

**Comment by markwkidd** [comment]
@nubecitas do you still have this issue with newer versions of mame2003?

**Comment by hizzlekizzle** [comment]
closing. feel free to open it back up if the problem persists

**Comment by Spartk** [comment]
I have the same sound issues. I installed Retroarch on my Psvita 2 days ago (latest version). I tried playing "Toki" with mame2003 core. Game runs perfectly except for the sound which is altered. Instead of the music I can only hear a sound like a bell playing the rhythm bass. Sound effects are correct, the music is wrong.
